### ISSUE TITLE
Add edit option to manage Launch Vehicles

### ISSUE THREAD

**Issue by Sawair** [JackCoiley/KerbalLaunchVehicles#3]
I think that options woud be nice: 
- change/add Launch Config of vehicles 
- delete/rename vehicle

If you need help/don't have time, I can help ;)

**Comment by JCoil** [comment]
You can do both these things with the current version!

It's not too obvious, but if you open the window in an empty VAB, you will see the list of vehicles on the Add/Edit Vehicle tab (leftmost button). Clicking one of these will open the vehicle for editing.

The only thing you can't do currently is delete a vehicle in game. However, if you don;'t mind a bit of file editing, you can just remove the entry in the config file and delete the relevant subassembly.

Thanks for the feedback!

**Comment by Sawair** [comment]
Ok, thx I didn't know about that
